### ISSUE TITLE
on macOS the program shut down immediately

### ISSUE THREAD

**Issue by salvob41** [glouw/pather#1]
I don't know if you had the chance to test it on macOS, but the program doesn't run properly. It opens a window and die immediately after. 

I have macOS v 10.13.3 (17D102)
It shows the following warning when building:
```
$ make 
gcc  -std=c99 -Wshadow -Wall -Wpedantic -Wextra -Wdouble-promotion -g -Ofast -march=native -MMD -MP -MT main.o -MF main.td -c main.c
main.c:534:15: warning: variable 'e' is used uninitialized whenever function 'main' is called
      [-Wsometimes-uninitialized]
    SDL_Event e;
    ~~~~~~~~~~^
main.c:536:69: note: uninitialized use occurs here
    for(const uint8_t* key = SDL_GetKeyboardState(NULL); !done(key, e); SDL_PollEvent(&e))
                                                                    ^
main.c:534:5: note: variable 'e' is declared here
    SDL_Event e;
    ^
1 warning generated.
gcc  -std=c99 -Wshadow -Wall -Wpedantic -Wextra -Wdouble-promotion -g -Ofast -march=native main.o  -lSDL2 -lm -o pather
```

but this shouldn't be a problem. 

When running with `./pather` 
the program will immediately shutdown, with a small window that appears and shutdown immediately.

**Comment by glouw** [comment]
I believe gcc aliases to clang on mac. Let me see what I can do.

**Comment by glouw** [comment]
if possible, run pather within valgrind and dump the log here:

    valgrind ./pather

**Comment by glouw** [comment]
Ive added checks to the init() system:

https://github.com/glouw/pather/blob/a7424c2491498e50c55479da7369ea2c818ed16e/main.c#L378

Dump the SDL crash log when your program dies.

**Comment by salvob41** [comment]
I think you did more than just a check. Now it works :D 

I think fixing the warning worked. 

Thank you! 

P.S.: valgrind does not work well in the new macOS :( https://stackoverflow.com/questions/40650338/valgrind-on-macos-sierra

**Comment by glouw** [comment]
That's sad to hear. Valgrind has no better.

I'm glad everything is working.
